name: ci/cd pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/hob:latest" .

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hob:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/hob:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/hob:latest
         
